name: Publish Docker image

on:
    push:
        branches:
            - main
    release:
        types: [published]

jobs:
    push_to_registry:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repo
              uses: actions/checkout@v5

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Extract version
              id: vars
              run: |
                  if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
                    echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
                  else
                    echo "VERSION=latest" >> $GITHUB_ENV
                  fi

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: |
                      thomastr/symfony-downloader:${{ env.VERSION }}
                      thomastr/symfony-downloader:latest
