name: Test

on: [ push ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-24.04

    env:
      APP_ENV: test
      APP_SECRET: $ecretf0rt3st
      YT_DLP_PATH: /usr/bin/true
      FFMPEG_PATH: /usr/bin/true
      MERCURE_URL: http://localhost/.well-known/mercure
      MERCURE_PUBLIC_URL: http://localhost/.well-known/mercure
      MERCURE_JWT_SECRET: '!ChangeThisMercureHubJWTSecretKey!'

    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: ⏱️ Set timezone
        run: |
          sudo timedatectl set-timezone Europe/Berlin
          timedatectl

      - name: 🛠️ Setup PHP extensions cache
        id: extcache
        uses: shivammathur/cache-extensions@9b476298b44f2e4d4268dd103ff4c3e216314e27 # 1.14.6
        with:
          key: ${{ runner.os }}-php-ext-${{ hashFiles('composer.lock') }}
          php-version: '8.5'
          extensions: ctype, iconv, mbstring

      - name: 🚀 Cache PHP extensions
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: 🛠️ Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: '8.5'
          ini-values: 'date.timezone=Europe/Berlin'
          extensions: ctype, iconv, mbstring
          tools: composer:v2

      - name: 🔎 Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: 🚀 Cache dependencies installed with composer
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: 💪 Install Dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --apcu-autoloader

      - name: 💨 Run tests
        run: vendor/bin/phpunit